version: '3.8'

services:
  app:
    build: .
    ports:
      - '3000:3000'
    depends_on:
      - mongodb
      - clamav
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/malwarebytes
      - CLAMAV_HOST=clamav
      - CLAMAV_PORT=3310
      - MINIO_ENDPOINT=http://minio:9000
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin

  mongodb:
    image: arm64v8/mongo:4.0
    platform: linux/arm64/v8
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - 'mongodb-data:/data/db'

  clamav:
    image: mkodockx/docker-clamav:latest
    volumes:
      - clamav_data:/var/lib/clamav
      - clamav_socket:/var/run/clamd.scan
    ports:
      - '3310:3310'
    restart: unless-stopped

  minio:
    image: minio/minio
    platform: linux/arm64/v8
    volumes:
      - minio_data:/data
    ports:
      - '9000:9000'
      - '9001:9001'
    command:
      - server
      - /export
      - --console-address
      - :9001
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:9000/minio/health/live']
      interval: 30s
      timeout: 20s
      retries: 3

  createbuckets:
    image: minio/mc
    platform: linux/arm64/v8
    depends_on:
      - minio
    entrypoint: >
      sh -c "
      mc alias set myminio http://minio:9000 minioadmin minioadmin;
      if ! mc ls myminio | grep -q 'malwarebytes'; then
        mc mb myminio/malwarebytes;
        mc policy set public myminio/malwarebytes;
      fi;
      exit 0;
      "

volumes:
  mongodb-data:
  clamav_data:
  clamav_socket:
  minio_data:
